"""add_composite_index_for_products

Revision ID: fd3ba78175d7
Revises: e2065f96b961
Create Date: 2026-09-21 17:07:23.256059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd3ba78175d7'
down_revision: Union[str, Sequence[str], None] = 'e2065f96b961'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_products_filtered_list', 'products', ['is_active', 'category_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_products_filtered_list', table_name='products')
    # ### end Alembic commands ###
